docs_dir: docs-source
site_name: Stated
site_dir: docs
site_url: https://realabja.github.com/stated/
repo_url: https://github.com/realabja/stated/
repo_name: Stated
theme:
  name: material
nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - 'Getting Started': 'getting-started.md'
  - 'Issue Tracker': 'https://github.com/realabja/stated/issues'
