[tool.poetry]
name = "stated"
version = "0.1.1a0"
description = "TODO"
authors = ["Abbas Jafari <abbas.jafari@powercoders.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
